packages:
  - apps/*
  - packages/*

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  node-pty: true
  sharp: true

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - node-pty
  - sharp
